
export const categories = [
  {
    name: "Food Processing Projects",
    slug: "food-processing",
    description: "Explore food processing and production opportunities under PMFME scheme",
    image:'/images/food-processing.jpg',
  },
  {
    name: "Service Sector Projects",
    slug: "service-sector",
    description: "Discover service-based business opportunities under PMEGP scheme",
    image: "/images/service-sector.jpg",
  },
  {
    name: "Manufacturing Projects",
    slug: "manufacturing",
    description: "Explore manufacturing business opportunities under PMEGP scheme",
    image: '/images/manufacturing.jpg',
  },
  {name:"Trading Projects",
    slug:"/trading"
  }
]

export const tradingProjects = [
  {
    name: "Retail Trading of Consumer Goods",
    slug: "retail-trading-consumer-goods",
    description: "A retail trading unit for consumer goods like household products, groceries, and personal care items.",
    longDescription:
      "This project involves setting up a retail trading unit for sourcing and selling consumer goods such as household products, groceries, and personal care items. The unit will focus on local and regional markets, leveraging wholesale procurement and efficient inventory management.",
    categorySlug: "trading",
    scheme: "PMEGP",
    estimatedCost: "₹3L - ₹10L",
    timeline: "2-4 months",
    requirements: ["Shop space", "Inventory storage", "Point-of-sale system", "Delivery logistics"],
    machinery: [
      { name: "Point-of-Sale (POS) System", cost: "₹50,000" },
      { name: "Storage Shelves", cost: "₹30,000" },
      { name: "Billing Software", cost: "₹20,000" },
      { name: "Delivery Vehicle (optional)", cost: "₹2,00,000" },
    ],
    landRequirement: "200-500 sq. ft.",
    powerRequirement: "1-3 KW",
    manpower: "3-5 persons",
    rawMaterials: ["Groceries", "Household products", "Personal care items", "Packaging materials"],
    marketPotential: "High demand in urban and semi-urban markets",
    profitMargin: "15-25%",
    breakEven: "8-12 months",
    subsidyDetails: "25-35% subsidy under PMEGP scheme for eligible applicants",
    documents: [
      "Identity Proof (Aadhaar/PAN)",
      "Address Proof",
      "Bank Account Details",
      "Project Report",
      "Shop/Establishment License",
      "GST Registration",
    ],
  },
  {
    name: "Wholesale Trading of Agricultural Products",
    slug: "wholesale-trading-agricultural-products",
    description: "A wholesale trading unit for sourcing and distributing agricultural products like grains, pulses, and spices.",
    longDescription:
      "This project involves establishing a wholesale trading unit for agricultural products such as grains, pulses, and spices. The unit will source products directly from farmers or mandis and distribute to retailers or bulk buyers in regional markets.",
    categorySlug: "trading",
    scheme: "PMEGP",
    estimatedCost: "₹5L - ₹15L",
    timeline: "3-5 months",
    requirements: ["Warehouse space", "Inventory management system", "Transport logistics", "Weighing equipment"],
    machinery: [
      { name: "Weighing Scales", cost: "₹50,000" },
      { name: "Storage Bins and Racks", cost: "₹1,00,000" },
      { name: "Inventory Management Software", cost: "₹30,000" },
      { name: "Transport Vehicle", cost: "₹3,00,000" },
    ],
    landRequirement: "800-1500 sq. ft.",
    powerRequirement: "2-5 KW",
    manpower: "5-8 persons",
    rawMaterials: ["Grains", "Pulses", "Spices", "Packaging materials"],
    marketPotential: "High demand in regional and urban markets",
    profitMargin: "10-20%",
    breakEven: "12-18 months",
    subsidyDetails: "25-35% subsidy under PMEGP scheme for eligible applicants",
    documents: [
      "Identity Proof (Aadhaar/PAN)",
      "Address Proof",
      "Bank Account Details",
      "Project Report",
      "Trade License",
      "GST Registration",
    ],
  },
];

export const foodProcessingProjects = [
  {
    name: "Flour Mill Unit",
    slug: "flour-mill-unit",
    description: "A small-scale flour mill unit for processing wheat and other grains into flour.",
    longDescription:
      "This project involves setting up a small-scale flour mill unit that processes wheat and other grains into flour. The unit will be equipped with modern milling machinery to ensure high-quality flour production. The project aims to cater to local markets with fresh, quality flour products.",
    categorySlug: "food-processing",
    scheme: "PMFME",
    estimatedCost: "₹5L - ₹15L",
    timeline: "3-6 months",
    requirements: [
      "Flour milling machinery",
      "Storage space for raw materials",
      "Packaging equipment",
      "Quality testing tools",
    ],
    machinery: [
      { name: "Flour Mill Machine (10HP)", cost: "₹2,50,000" },
      { name: "Grain Cleaner", cost: "₹75,000" },
      { name: "Packaging Machine", cost: "₹1,00,000" },
      { name: "Storage Bins", cost: "₹50,000" },
      { name: "Quality Testing Equipment", cost: "₹25,000" },
    ],
    landRequirement: "500-1000 sq. ft.",
    powerRequirement: "10-15 HP",
    manpower: "3-5 persons",
    rawMaterials: ["Wheat", "Other grains (optional)", "Packaging materials"],
    marketPotential: "High demand in local markets, bakeries, and retail stores",
    profitMargin: "15-20%",
    breakEven: "12-18 months",
    subsidyDetails: "35% capital subsidy under PMFME scheme for eligible applicants",
    documents: [
      "Identity Proof (Aadhaar/PAN)",
      "Address Proof",
      "Bank Account Details",
      "Project Report",
      "Land/Property Documents",
      "FSSAI License",
    ],
  },
  {
    name: "Rice Mill Plant",
    slug: "rice-mill-plant",
    description: "A rice mill plant for processing paddy into polished rice with modern equipment.",
    longDescription:
      "This project involves setting up a rice mill plant for processing paddy into polished rice. The unit will be equipped with modern rice milling machinery to ensure high-quality rice production. The project aims to cater to local markets with fresh, quality rice products.",
    categorySlug: "food-processing",
    scheme: "PMFME",
    estimatedCost: "₹15L - ₹50L",
    timeline: "6-9 months",
    requirements: ["Rice milling machinery", "Paddy cleaner and separator", "Destoner machine", "Packaging unit"],
    machinery: [
      { name: "Rice Huller", cost: "₹3,50,000" },
      { name: "Paddy Separator", cost: "₹2,00,000" },
      { name: "Destoner", cost: "₹1,50,000" },
      { name: "Whitener", cost: "₹2,50,000" },
      { name: "Packaging Unit", cost: "₹1,00,000" },
    ],
    landRequirement: "1000-2000 sq. ft.",
    powerRequirement: "20-30 HP",
    manpower: "5-8 persons",
    rawMaterials: ["Paddy", "Packaging materials"],
    marketPotential: "High demand in local markets and retail stores",
    profitMargin: "15-25%",
    breakEven: "18-24 months",
    subsidyDetails: "35% capital subsidy under PMFME scheme for eligible applicants",
    documents: [
      "Identity Proof (Aadhaar/PAN)",
      "Address Proof",
      "Bank Account Details",
      "Project Report",
      "Land/Property Documents",
      "FSSAI License",
    ],
  },
  {
    name: "Spice Manufacturing Unit",
    slug: "spice-manufacturing-unit",
    description: "A unit for processing and packaging various spices with grinding and blending facilities.",
    longDescription:
      "This project involves setting up a spice manufacturing unit for processing and packaging various spices. The unit will be equipped with modern grinding and blending machinery to ensure high-quality spice production. The project aims to cater to local markets with fresh, quality spice products.",
    categorySlug: "food-processing",
    scheme: "PMFME",
    estimatedCost: "₹10L - ₹25L",
    timeline: "4-8 months",
    requirements: ["Spice grinding machines", "Blending equipment", "Packaging machinery", "Storage facilities"],
    machinery: [
      { name: "Spice Grinder", cost: "₹2,00,000" },
      { name: "Blending Machine", cost: "₹1,50,000" },
      { name: "Packaging Machine", cost: "₹1,00,000" },
      { name: "Storage Racks", cost: "₹50,000" },
      { name: "Quality Testing Equipment", cost: "₹25,000" },
    ],
    landRequirement: "500-1000 sq. ft.",
    powerRequirement: "10-15 HP",
    manpower: "3-5 persons",
    rawMaterials: ["Raw spices", "Packaging materials"],
    marketPotential: "High demand in local markets, retail stores, and online platforms",
    profitMargin: "20-30%",
    breakEven: "12-18 months",
    subsidyDetails: "35% capital subsidy under PMFME scheme for eligible applicants",
    documents: [
      "Identity Proof (Aadhaar/PAN)",
      "Address Proof",
      "Bank Account Details",
      "Project Report",
      "Land/Property Documents",
      "FSSAI License",
    ],
  },
]

export const serviceProjects = [
  {
    name: "Digital Service Center",
    slug: "digital-service-center",
    description: "A center offering various digital services like printing, scanning, online form filling, etc.",
    longDescription:
      "This project involves setting up a digital service center offering various services like printing, scanning, online form filling, etc. The center will be equipped with modern computers, printers, and scanners to provide quality services to customers.",
    categorySlug: "service-sector",
    scheme: "PMEGP",
    estimatedCost: "₹2L - ₹5L",
    timeline: "1-2 months",
    requirements: ["Computers and peripherals", "Internet connection", "Printer and scanner", "Office space"],
    machinery: [
      { name: "Computers (3 units)", cost: "₹1,50,000" },
      { name: "Printer/Scanner/Copier", cost: "₹50,000" },
      { name: "UPS and Backup", cost: "₹25,000" },
      { name: "Furniture and Fixtures", cost: "₹50,000" },
    ],
    landRequirement: "200-300 sq. ft.",
    powerRequirement: "2-3 KW",
    manpower: "2-3 persons",
    rawMaterials: ["Paper", "Ink/Toner", "Stationery items"],
    marketPotential: "High demand in rural and semi-urban areas",
    profitMargin: "30-40%",
    breakEven: "8-12 months",
    subsidyDetails: "25-35% subsidy under PMEGP scheme for eligible applicants",
    documents: [
      "Identity Proof (Aadhaar/PAN)",
      "Address Proof",
      "Bank Account Details",
      "Project Report",
      "Shop & Establishment License",
    ],
  },
  {
    name: "Mobile Repairing Center",
    slug: "mobile-repairing-center",
    description: "A service center for repairing and servicing mobile phones and accessories.",
    longDescription:
      "This project involves setting up a mobile repairing center for repairing and servicing mobile phones and accessories. The center will be equipped with modern tools and equipment to provide quality repair services to customers.",
    categorySlug: "service-sector",
    scheme: "PMEGP",
    estimatedCost: "₹3L - ₹7L",
    timeline: "1-3 months",
    requirements: ["Repair tools and equipment", "Testing devices", "Spare parts inventory", "Shop space"],
    machinery: [
      { name: "Soldering Station", cost: "₹25,000" },
      { name: "Microscope", cost: "₹30,000" },
      { name: "Testing Equipment", cost: "₹50,000" },
      { name: "Spare Parts Inventory", cost: "₹1,00,000" },
      { name: "Furniture and Fixtures", cost: "₹50,000" },
    ],
    landRequirement: "200-300 sq. ft.",
    powerRequirement: "1-2 KW",
    manpower: "2-3 persons",
    rawMaterials: ["Spare parts", "Consumables", "Packaging materials"],
    marketPotential: "High demand in urban and semi-urban areas",
    profitMargin: "30-40%",
    breakEven: "10-14 months",
    subsidyDetails: "25-35% subsidy under PMEGP scheme for eligible applicants",
    documents: [
      "Identity Proof (Aadhaar/PAN)",
      "Address Proof",
      "Bank Account Details",
      "Project Report",
      "Shop & Establishment License",
    ],
  },
]

export const manufacturingProjects = [
  {
    name: "Readymade Garments Manufacturing",
    slug: "readymade-garments-manufacturing",
    description: "A unit for manufacturing readymade garments with cutting, stitching, and finishing facilities.",
    longDescription:
      "This project involves setting up a readymade garments manufacturing unit with cutting, stitching, and finishing facilities. The unit will be equipped with modern sewing machines and other equipment to produce quality garments for local and regional markets.",
    categorySlug: "manufacturing",
    scheme: "PMEGP",
    estimatedCost: "₹5L - ₹20L",
    timeline: "3-6 months",
    requirements: ["Sewing machines", "Cutting equipment", "Finishing tools", "Production space"],
    machinery: [
      { name: "Industrial Sewing Machines (10 units)", cost: "₹3,00,000" },
      { name: "Cutting Table and Equipment", cost: "₹50,000" },
      { name: "Ironing and Finishing Equipment", cost: "₹75,000" },
      { name: "Storage Racks", cost: "₹50,000" },
    ],
    landRequirement: "500-1000 sq. ft.",
    powerRequirement: "5-8 KW",
    manpower: "10-15 persons",
    rawMaterials: ["Fabric", "Thread", "Buttons and accessories", "Packaging materials"],
    marketPotential: "High demand in local and regional markets",
    profitMargin: "20-30%",
    breakEven: "12-18 months",
    subsidyDetails: "25-35% subsidy under PMEGP scheme for eligible applicants",
    documents: [
      "Identity Proof (Aadhaar/PAN)",
      "Address Proof",
      "Bank Account Details",
      "Project Report",
      "Factory License",
      "GST Registration",
    ],
  },
  {
    name: "Soap Manufacturing Unit",
    slug: "soap-manufacturing-unit",
    description:
      "A facility for manufacturing various types of soaps with mixing, molding, and packaging capabilities.",
    longDescription:
      "This project involves setting up a soap manufacturing unit for producing various types of soaps. The unit will be equipped with mixing, molding, and packaging machinery to produce quality soap products for local and regional markets.",
    categorySlug: "manufacturing",
    scheme: "PMEGP",
    estimatedCost: "₹3L - ₹15L",
    timeline: "2-5 months",
    requirements: ["Soap making equipment", "Mixing tanks", "Molds", "Cutting and packaging machinery"],
    machinery: [
      { name: "Soap Mixer", cost: "₹1,00,000" },
      { name: "Soap Molds", cost: "₹50,000" },
      { name: "Cutting Machine", cost: "₹75,000" },
      { name: "Packaging Machine", cost: "₹1,00,000" },
      { name: "Storage Racks", cost: "₹25,000" },
    ],
    landRequirement: "500-800 sq. ft.",
    powerRequirement: "3-5 KW",
    manpower: "5-8 persons",
    rawMaterials: ["Oils and fats", "Caustic soda", "Fragrances", "Packaging materials"],
    marketPotential: "High demand in local and regional markets",
    profitMargin: "25-35%",
    breakEven: "10-15 months",
    subsidyDetails: "25-35% subsidy under PMEGP scheme for eligible applicants",
    documents: [
      "Identity Proof (Aadhaar/PAN)",
      "Address Proof",
      "Bank Account Details",
      "Project Report",
      "Factory License",
      "GST Registration",
    ],
  },
]

export const governmentSchemes = [
  {
    name: "Prime Minister's Employment Generation Programme (PMEGP)",
    slug: "pmegp",
    description: "A credit-linked subsidy program to facilitate self-employment through micro-enterprise establishment",
    ministry: "Ministry of Micro, Small & Medium Enterprises",
    eligibility: [
      "Individuals above 18 years of age",
      "VIII Std. pass for projects above ₹10 lakh in manufacturing and above ₹5 lakh in service sector",
      "Self Help Groups",
      "Charitable Trusts",
      "Institutions registered under Societies Registration Act 1860",
    ],
    benefits: [
      "Subsidy of 15-35% for urban areas and 25-35% for rural areas",
      "Maximum project cost of ₹25 lakh for manufacturing and ₹10 lakh for service sector",
      "Minimal owner contribution (5-10%)",
      "Bank loan at affordable rates for remaining amount",
    ],
    applicationProcess: [
      "Online application through PMEGP e-portal",
      "Selection through District Task Force Committee",
      "EDP Training (mandatory)",
      "Bank sanction and disbursement",
      "Subsidy release",
    ],
    documents: [
      "Identity Proof (Aadhaar/Voter ID)",
      "Address Proof",
      "Educational Qualification Certificate",
      "Project Report",
      "Passport size photographs",
      "Caste Certificate (if applicable)",
    ],
    sectors: ["Manufacturing", "Service", "Trading (except prohibited items)"],
    status: "Active",
    website: "https://pmegp.gov.in",
  },
  {
    name: "PM Formalization of Micro Food Processing Enterprises (PMFME)",
    slug: "pmfme",
    description:
      "A centrally sponsored scheme for providing financial, technical and business support for upgradation of micro food processing enterprises",
    ministry: "Ministry of Food Processing Industries",
    eligibility: [
      "Existing micro food processing enterprises",
      "Farmer Producer Organizations (FPOs)",
      "Self Help Groups (SHGs)",
      "Cooperatives",
      "Individual entrepreneurs",
    ],
    benefits: [
      "Credit-linked capital subsidy @35% of eligible project cost with maximum ceiling of ₹10 lakh",
      "Seed capital to SHGs for working capital and purchase of small tools",
      "Training and handholding support",
      "Marketing and branding support",
    ],
    applicationProcess: [
      "Application through State Nodal Agency or District Resource Person",
      "Preparation of DPR (Detailed Project Report)",
      "Approval by State/District Level Committee",
      "Bank sanction and disbursement",
      "Subsidy release",
    ],
    documents: [
      "Identity Proof (Aadhaar/Voter ID)",
      "Address Proof",
      "Bank Account Details",
      "Detailed Project Report",
      "Land/Property Documents",
      "FSSAI License/Registration",
    ],
    sectors: [
      "Food Processing",
      "Fruits & Vegetables Processing",
      "Dairy Products",
      "Meat & Poultry Processing",
      "Fisheries",
      "Bakery & Confectionery",
      "Spices & Plantation Crops Processing",
    ],
    status: "Active",
    website: "https://pmfme.mofpi.gov.in",
  },
  {
    name: "Pradhan Mantri Mudra Yojana (PMMY)",
    slug: "mudra",
    description: "Financial support for non-corporate, non-farm small/micro enterprises through loans up to ₹10 lakh",
    ministry: "Ministry of Finance",
    eligibility: ["Small businesses", "Entrepreneurs", "Self-employed individuals", "Startups", "Women entrepreneurs"],
    benefits: [
      "Shishu: Loans up to ₹50,000",
      "Kishore: Loans from ₹50,001 to ₹5 lakh",
      "Tarun: Loans from ₹5,00,001 to ₹10 lakh",
      "No collateral required",
      "Minimal documentation",
    ],
    applicationProcess: [
      "Apply through commercial banks, RRBs, Small Finance Banks, NBFCs, MFIs",
      "Submit required documents",
      "Loan approval and disbursement",
    ],
    documents: [
      "Identity Proof",
      "Address Proof",
      "Business Plan/Proposal",
      "Proof of business existence (if applicable)",
      "Bank Account Details",
    ],
    sectors: ["Manufacturing", "Trading", "Services", "Agriculture and Allied Activities"],
    status: "Active",
    website: "https://www.mudra.org.in",
  },
  {
    name: "Stand-Up India Scheme",
    slug: "stand-up-india",
    description: "Promotes entrepreneurship among women, SC/ST communities by providing bank loans for setting up greenfield enterprises",
    ministry: "Ministry of Finance",
    eligibility: [
      "SC/ST or women entrepreneurs above 18 years of age",
      "Enterprises in manufacturing, services, or trading sector",
      "For greenfield projects only",
      "Applicant must hold at least 51% of shareholding/control",
    ],
    benefits: [
      "Loans between ₹10 lakh and ₹1 crore",
      "Composite loan (including term loan and working capital)",
      "Margin money of 10-25% required",
      "Handholding support through dedicated portal",
    ],
    applicationProcess: [
      "Apply through Stand-Up India portal or banks",
      "Submit detailed project report",
      "Loan approval by banks",
      "Disbursement after compliance",
    ],
    documents: [
      "Identity Proof (Aadhaar/Voter ID)",
      "Address Proof",
      "Caste Certificate (if applicable)",
      "Business Plan",
      "Bank Account Details",
      "Proof of business premises",
    ],
    sectors: ["Manufacturing", "Services", "Trading"],
    status: "Active",
    website: "https://www.standupmitra.in",
  },
  {
    name: "Startup India Seed Fund Scheme",
    slug: "startup-india-seed-fund",
    description: "Provides financial assistance to startups for proof of concept, prototype development, and market entry",
    ministry: "Department for Promotion of Industry and Internal Trade (DPIIT)",
    eligibility: [
      "Startups recognized by DPIIT",
      "Incorporated not more than 2 years ago",
      "Annual turnover not exceeding ₹1 crore",
      "Not received funding more than ₹10 lakh under any other government scheme",
    ],
    benefits: [
      "Up to ₹20 lakh for proof of concept/prototype",
      "Up to ₹50 lakh for market entry, commercialization",
      "Funding through incubators",
      "Equity stake option for incubators",
    ],
    applicationProcess: [
      "Apply through incubators empanelled under the scheme",
      "Evaluation by Incubator Seed Management Committee",
      "Fund disbursement through incubators",
    ],
    documents: [
      "DPIIT recognition certificate",
      "Business Plan",
      "Identity Proof of founders",
      "Incorporation Certificate",
      "Financial statements (if applicable)",
    ],
    sectors: ["All DPIIT-recognized startup sectors"],
    status: "Active",
    website: "https://seedfund.startupindia.gov.in",
  },
  {
    name: "MSME Idea Hackathon Scheme",
    slug: "msme-idea-hackathon",
    description: "Encourages innovative ideas from MSMEs and startups to address challenges in various sectors",
    ministry: "Ministry of Micro, Small & Medium Enterprises",
    eligibility: [
      "Registered MSMEs",
      "Startups recognized by DPIIT",
      "Individuals with innovative ideas",
      "Academic institutions and students",
    ],
    benefits: [
      "Financial support up to ₹15 lakh for idea development",
      "Mentorship and incubation support",
      "Access to investor networks",
      "Recognition and scaling opportunities",
    ],
    applicationProcess: [
      "Submit idea through MSME Idea Portal",
      "Evaluation by expert committee",
      "Shortlisting and pitching",
      "Fund disbursement and support",
    ],
    documents: [
      "Identity Proof",
      "MSME Registration/DPIIT Recognition (if applicable)",
      "Detailed Idea Proposal",
      "Proof of concept (if available)",
    ],
    sectors: ["Manufacturing", "Services", "Technology", "Sustainability"],
    status: "Active",
    website: "https://innovateindia.mygov.in",
  },
  {
    name: "NIDHI PRAYAS Scheme (National Initiative for Developing and Harnessing Innovations)",
    slug: "nidhi-prayas",
    description: "Supports innovators to develop prototypes from idea stage through funding and incubation",
    ministry: "Department of Science and Technology",
    eligibility: [
      "Individual innovators (Indian citizens)",
      "Startups with less than 2 years of incorporation",
      "Preference for technology-driven innovations",
      "No prior funding for the same idea",
    ],
    benefits: [
      "Funding up to ₹10 lakh for prototype development",
      "Access to PRAYAS Centres for technical guidance",
      "Mentorship and networking support",
      "Opportunity for further funding under NIDHI programs",
    ],
    applicationProcess: [
      "Apply through PRAYAS Centre or DST portal",
      "Evaluation by Technical Expert Committee",
      "Prototype development support",
      "Progress monitoring",
    ],
    documents: [
      "Identity Proof",
      "Detailed Project Proposal",
      "Proof of Concept (if available)",
      "Incorporation Certificate (if startup)",
    ],
    sectors: ["Technology", "Healthcare", "Energy", "Agriculture", "Sustainability"],
    status: "Active",
    website: "https://nidhi-prayas.org",
  },
  {
    name: "Seed Support Scheme (Under NIDHI Cohort Incubators)",
    slug: "nidhi-seed-support",
    description: "Provides early-stage funding to startups incubated under NIDHI-supported incubators for scaling",
    ministry: "Department of Science and Technology",
    eligibility: [
      "Startups incubated at NIDHI-supported incubators",
      "Incorporated as a company",
      "Technology-driven ventures",
      "Scalable business model",
    ],
    benefits: [
      "Funding up to ₹1 crore (equity-based or soft loan)",
      "Access to incubation facilities",
      "Mentorship and market access support",
      "Networking with investors",
    ],
    applicationProcess: [
      "Apply through NIDHI-supported incubator",
      "Evaluation by Investment Committee",
      "Fund disbursement with milestones",
      "Monitoring and reporting",
    ],
    documents: [
      "DPIIT recognition (if applicable)",
      "Business Plan",
      "Financial Projections",
      "Incorporation Certificate",
      "Incubator endorsement letter",
    ],
    sectors: ["Technology", "Healthcare", "Energy", "Agriculture", "Sustainability"],
    status: "Active",
    website: "https://nidhi-sss.dst.gov.in",
  },
];
